# Generated by Django 5.2.7 on 2025-11-05 12:40

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Número ou identificador do quarto (ex: 101, 203A)', max_length=10, unique=True)),
                ('andar', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('Disponivel', 'Disponível'), ('Ocupado', 'Ocupado'), ('Manutencao', 'Em Manutenção'), ('Limpeza', 'Em Limpeza')], default='Disponivel', max_length=20)),
            ],
            options={
                'verbose_name': 'Quarto',
                'verbose_name_plural': 'Quartos',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='ServicoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Serviço Adicional',
                'verbose_name_plural': 'Serviços Adicionais',
            },
        ),
        migrations.CreateModel(
            name='TipoQuarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('preco_diaria', models.DecimalField(decimal_places=2, help_text='Preço da diária para este tipo de quarto', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('capacidade', models.IntegerField(help_text='Número máximo de hóspedes que o quarto suporta', validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'Tipo de Quarto',
                'verbose_name_plural': 'Tipos de Quarto',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo', models.CharField(choices=[('Hospede', 'Hóspede'), ('Recepcionista', 'Recepcionista'), ('Gerente', 'Gerente')], default='Hospede', help_text='Tipo de usuário no sistema', max_length=20)),
                ('cpf', models.CharField(blank=True, help_text='CPF no formato XXX.XXX.XXX-XX', max_length=14, null=True, unique=True)),
                ('telefone', models.CharField(blank=True, help_text='Telefone com DDD, ex: (XX) 9XXXX-XXXX', max_length=20, null=True)),
                ('data_nascimento', models.DateField(blank=True, help_text='Data de nascimento no formato AAAA-MM-DD', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_checkin', models.DateField(help_text='Data de entrada')),
                ('data_checkout', models.DateField(help_text='Data de saída')),
                ('num_hospedes', models.IntegerField(help_text='Número total de hóspedes na reserva', validators=[django.core.validators.MinValueValidator(1)])),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor total calculado da estadia (diárias * preço)', max_digits=10)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Confirmada', 'Confirmada'), ('Checkin', 'Check-in Realizado'), ('Checkout', 'Checkout Realizado'), ('Cancelada', 'Cancelada')], default='Pendente', max_length=20)),
                ('data_reserva', models.DateTimeField(auto_now_add=True)),
                ('valor_reembolso', models.DecimalField(blank=True, decimal_places=2, help_text='Valor a ser reembolsado em caso de cancelamento', max_digits=10, null=True)),
                ('hospede', models.ForeignKey(limit_choices_to={'tipo': 'Hospede'}, on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to=settings.AUTH_USER_MODEL)),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='backend.quarto')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('Solicitado', 'Solicitado'), ('Em_Andamento', 'Em Andamento'), ('Concluido', 'Concluído'), ('Cancelado', 'Cancelado')], default='Solicitado', max_length=20)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, help_text='Valor total (serviço * quantidade)', max_digits=10)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos_solicitados', to='backend.reserva')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to='backend.servicoadicional')),
            ],
            options={
                'verbose_name': 'Solicitação de Serviço',
                'verbose_name_plural': 'Solicitações de Serviços',
            },
        ),
        migrations.AddField(
            model_name='quarto',
            name='tipo_quarto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quartos', to='backend.tipoquarto'),
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(help_text='Nota de 1 a 5 estrelas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True)),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('hospede', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes_feitas', to=settings.AUTH_USER_MODEL)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao', to='backend.reserva')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'unique_together': {('reserva', 'hospede')},
            },
        ),
    ]
