# Generated by Django 5.2.7 on 2025-10-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('endereco', models.TextField()),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('gerente_responsavel', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(default='ativa', max_length=10)),
            ],
            options={
                'db_table': 'agencia',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('endereco', models.TextField(blank=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='ativo', max_length=10)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('codigo_agencia', models.CharField(max_length=20)),
                ('cpf_titular', models.CharField(max_length=14)),
                ('tipo', models.CharField(max_length=10)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('data_abertura', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='ativa', max_length=10)),
                ('limite_saque_diario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'db_table': 'conta',
            },
        ),
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_conta', models.CharField(max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=12)),
                ('descricao', models.TextField(blank=True)),
                ('caixa_operador', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'db_table': 'deposito',
            },
        ),
        migrations.CreateModel(
            name='Saque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_conta', models.CharField(max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('local', models.CharField(max_length=20)),
                ('caixa_operador', models.CharField(blank=True, max_length=120)),
                ('status_operacao', models.CharField(default='aprovado', max_length=10)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'saque',
            },
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conta_origem', models.CharField(max_length=30)),
                ('conta_destino', models.CharField(max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=12)),
                ('descricao', models.TextField(blank=True)),
                ('status', models.CharField(default='processando', max_length=12)),
                ('operador', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'db_table': 'transferencia',
            },
        ),
    ]
